version: "3"
services:
  node:
    container_name: techdao

    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - app:/app
      - ./shared:/app/shared

    ports:
      - "8545:8545"

    networks:
      - backend-network

networks:
  backend-network:
    
volumes:
  app: